### ISSUE TITLE
mkindex on both strands?

### ISSUE THREAD

**Issue by FrVan** [genometools/genometools#816] opened 2016-07-07 13:58 UTC
Hi,

I am trying to use the mkindex program to find all 20-mers with a minimal occurrence (10 in my example) but I need the program to check both strands of my sequences. I don't know if this is possible but I found the -mirrored option in the suffixerator program. When I use this option to construct the esa, I get an error message when I run mkindex. Is this a bug or is it simply not possible to search on both strands?

These commands work:
```
gt suffixerator -dna -pl -tis -suf -lcp -v -db seqs.fas -indexname seqs
gt tallymer mkindex -minocc 10 -mersize 20 -esa seqs
```

These commands give me an error:
```
gt suffixerator -dna -pl -tis -suf -lcp -mirrored -v -db seqs.fas -indexname mirrored
gt tallymer mkindex -minocc 10 -mersize 20 -esa mirrored
```

error message:
```
gt tallymer mkindex -minocc 10 -mersize 20 -esa mirrored
Assertion failed: (len >= 1UL && encseq != NULL && startpos + len <= encseq->totallength), function gt_encseq_contains_special, file src/core/encseq.c, line 696.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with `gt -version`.
Aborted (core dumped)
```

I am using GenomeTools version: 1.5.8 in Windows (gt-1.5.8-CYGWIN_NT-10.0_i686-32bit). 

Thanks

**Comment by Garonenur** [comment] 2016-07-07 14:28
Hi @FrVan 

I tested your commands and the error seems gone in the current version of gt, which is 1.5.9 (and will soon be 1.5.10). If possible could you update your gt and try again?

**Comment by Garonenur** [comment] 2016-07-07 14:32
Sorry, clarification: the latest release version is 1.5.8! The current development-version here from GitHub seems to have fixed this problem, so if possible try to download the latest version here from github.

**Comment by satta** [comment] 2016-07-07 16:41
It looks like Tallymer doesn't realize that the sequence needs to be mirrored again when loading an index based on a mirrored sequence. I can reproduce this problem with the most recent version as well -- this is also dependent on the sequence used. I just tried it with:
```
gt suffixerator -dna -pl -tis -suf -lcp -mirrored -v -db testdata/at1MB -indexname mirrored
gt tallymer mkindex -minocc 10 -mersize 20 -esa mirrored
```
and encountered the same issue as @FrVan.

AFAICS Tallymer should read the `mirrored.prj file that comes with the index and if it has `mirrored=1`it needs to make sure `gt_encseq_mirror()` is done. I'll take a look later.

**Comment by satta** [comment] 2016-07-08 09:01
I have debugged this and it's not the automatic mirroring -- that's handled correctly in `inputsuffixarray()` in `src/match/esa-map.c`. The problem was that the method `gt_encseq_contains_special()` which is only used in Tallymer did not do the input coordinate transformation required for mirrored sequence support. I have added a pull request implementing this (maybe @stefan-kurtz could have another quick look?) and the Tallymer run finished for me afterwards. 

BTW, please be aware that using the `-mirrored` option treats the input as the _concatenation_ of the forward and reverse sequence, so make sure you interpret the resulting counts correctly.

**Comment by satta** [comment] 2016-07-08 09:19
@FrVan as you are using the Windows version: this fix will make it into the upcoming 1.5.9 release for which we will also provide Windows executables as part of our regular release. If it's urgent just let me know and I'll build a Windows version of the current development version once the fix has been merged.

**Comment by Garonenur** [comment] 2016-07-08 09:22
I will merge the PR asap, I am just wondering why I could get tallymer to run, the second time I tried it (without an error). I thought this was due to using the recent version I just compiled, and not the older version installed on my system.

**Comment by satta** [comment] 2016-07-08 09:24
AFAICS this is also input dependent, you will need to give it a sequence long enough to work with, that also produces some results triggering the problematic case. What did you use as example input?

**Comment by Garonenur** [comment] 2016-07-08 09:48
I used one file from testdata/genomediff - the thing is, it triggered the above mentioned assertion, but the second time I ran it, it just produced normal output. I didn't delete the files in between and reran both commands, just the tallymer part.

**Closed** 2016-07-08 09:54 UTC
Labels: bug
