### ISSUE TITLE
make: *** [obj/src/core/encseq.o] Error 1

### ISSUE THREAD

**Issue by 123123456abc** [genometools/genometools#983] opened 2021-07-14 14:10 UTC
[compile encseq.o]
In file included from /home/cjwen/software/genometools-1.6.2/src/core/sequence_buffer_fasta.h:21,
                 from src/core/encseq.c:57:
/home/cjwen/software/genometools-1.6.2/src/core/sequence_buffer.h:36: error: redefinition of typedef 'GtSequenceBuffer'
/home/cjwen/software/genometools-1.6.2/src/core/sequence_buffer_dust.h:26: note: previous declaration of 'GtSequenceBuffer' was here
make: *** [obj/src/core/encseq.o] Error 1

**Comment by satta** [comment] 2021-07-14 15:05
Can you provide a little more information about your compiler (e.g. GCC, version, ,..) and platform (e.g. RedHat Linux, macOS, etc. + version)? Also, please state your `make` command line invocation. Thanks! This would help us to reproduce the issue.

**Comment by 123123456abc** [comment] 2021-08-19 01:39
I'm sorry.
My order is : make prefix=/home/cjwen/software/genometools-1.6.2/gt install
platform : linux
compiler : make 3.81

**Comment by btrainee** [comment] 2021-08-30 08:18
i have the same problem!

**Comment by satta** [comment] 2021-09-07 11:45
> I'm sorry.
> My order is : make prefix=/home/cjwen/software/genometools-1.6.2/gt install
> platform : linux
> compiler : make 3.81

Thanks. Could you also do a 
```
gcc -v 
```
to let me know your compiler version (`make` is not a compiler). I am asking because for me everything builds fine, and I am trying to find out how to reproduce the issue/

Also. what distribution do you use?

**Comment by yuwanziaaa** [comment] 2024-02-29 13:25
src/match/eis-bwtseq-context.c: In function ‘gt_BWTSCRFGet’:
src/match/eis-bwtseq-context.c:291:39: error: ‘cxm’ directive output may be truncated writing 3 bytes into a region of size between 2 and 6 [-Werror=format-truncation=]
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |                                       ^~~
In file included from /usr/include/stdio.h:894,
                 from src/match/eis-bwtseq-context.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output between 6 and 10 bytes into a destination of size 8
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
src/match/eis-bwtseq-context.c: In function ‘gt_BWTSeqCRLoad’:
src/match/eis-bwtseq-context.c:291:39: error: ‘cxm’ directive output may be truncated writing 3 bytes into a region of size between 2 and 6 [-Werror=format-truncation=]
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |                                       ^~~
In file included from /usr/include/stdio.h:894,
                 from src/match/eis-bwtseq-context.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output between 6 and 10 bytes into a destination of size 8
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
src/match/eis-bwtseq-context.c:291:39: error: ‘cxm’ directive output may be truncated writing 3 bytes into a region of size between 2 and 6 [-Werror=format-truncation=]
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |                                       ^~~
In file included from /usr/include/stdio.h:894,
                 from src/match/eis-bwtseq-context.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output between 6 and 10 bytes into a destination of size 8
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:811: obj/src/match/eis-bwtseq-context.o] Error 1
make: *** Waiting for unfinished jobs....

My problem is the error message above，how to resovle this problem ? Because the software what I use is depending on the gt-version-1.5.9. I need your help.

**Comment by satta** [comment] 2024-02-29 13:58
Can you please open an new issue for your report because it seems to be a different thing.
You might also be able to continue with
```
make cleanup
```
and then
```
make errorcheck=no 
```
(please add your custom `make` parameters as you did before, just make sure `errorcheck=no` is in it)

**Comment by satta** [comment] 2024-03-04 10:00
Closing this with the recommendation to use the most recent version, in which this issue is  fixed.

**Closed by satta** 2024-03-04 10:00 UTC
Labels: support, needs information
