### ISSUE TITLE
gt ltrclustering error

### ISSUE THREAD

**Issue by paperonion** [genometools/genometools#925] opened 2019-11-13 12:42 UTC
## Problem description
I tried to cluster my ltrdigest output, and encountered a bug. I am hoping you would be willing to help me out.
EDIT: now with actual error code:
Assertion failed: (eb->plainseq), function gt_encseq_builder_build, file src/core/encseq.c, line 9060.

## Exact command line call triggering the problem
gt ltrclustering -psmall 80 -plarge 30 bSylAtr1.pri.cur.20190916.fasta Sylvatri_ltrdigest_output.gff2.txt

## file 1 - link to genome assembly:
https://s3.amazonaws.com/genomeark/species/Sylvia_atricapilla/bSylAtr1/assembly_curated/bSylAtr1.pri.cur.20190916.fasta.gz
## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
gt (GenomeTools) 1.5.9

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
-

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
-bash-4.2$ uname -r
3.10.0-514.2.2.el7.x86_64
-bash-4.2$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
[Sylvatri_ltrdigest_output.gff2.txt](https://github.com/genometools/genometools/files/3841124/Sylvatri_ltrdigest_output.gff2.txt)

Codename:       Core

**Comment by satta** [comment] 2019-11-29 21:06
The problem is here that you supply the GFF file with the FASTA headers (e.g. `scaffold_78_arrow_ctg1`) as sequence IDs (first column) but the version of `gt ltrclustering` expects the input to be in the legacy LTRharvest/LTRdigest format, which requires the sequence IDs to be `seqX` where X is the index of the sequence in the original FASTA file (i.e. `scaffold_100_arrow_ctg1` would be `seq0`, `scaffold_101_arrow_ctg1` would be `seq1`, and so on). 
Please keep in mind that `gt ltrclustering` is an experimental tool that was only meant to be used during the development of LTRsift, which is currently not actively maintained!
It might be possible to convert the GFF file to the legacy format by using a script to map sequence IDs between these two formats.

**Comment by satta** [comment] 2019-11-29 21:07
As for the uninformative error message, I will submit a patch to GenomeTools that makes sure a better error message is printed. You found a bug there 👍

**Comment by satta** [comment] 2019-12-01 18:39
Closing this issue as well as the duplicate. Please feel free to reply or open another issue if anything else comes up.

**Closed by satta** 2019-12-01 18:39 UTC
Labels: bug
