### ISSUE TITLE
gt ltrclustering：Assertion failed: (eb->plainseq)

### ISSUE THREAD

**Issue by SCQUchenyang** [genometools/genometools#912] opened 2019-03-06 11:33 UTC
Dear Sir，
When  I used the gt clustering(the command :gt ltrclustering -psmall 80 -plarge 30 genome.fa rename_hic.fa.pass.list.gff3) ,I encountered a question:
##
Assertion failed: (eb->plainseq), function gt_encseq_builder_build, file src/core/encseq.c, line 9098.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with `gt -version`.
zsh: abort (core dumped)  gt ltrclustering -psmall 80 -plarge 30 genome.fa rename_hic.fa.pass.list.gff3
##
I have got the LTR gff by ltr-retriever and the index is made by "gt suffixerator -db rename_hic.fa -indexname genome.fa -tis -suf -lcp -des -ssp -sds -dna".
Can you give me some tips about?
Thank for your work and time!
Chenyang

**Comment by satta** [comment] 2019-05-18 20:58
Hey, sorry for the delay in replying. Do you have a test input data for `gt ltrclustering` to reproduce the issue? Please note that this tool is experimental (mainly as a test driver for a component in LTRsift) and not guaranteed to work on all input data sets.

**Comment by satta** [comment] 2019-11-29 21:17
This is a potential duplicate of #925 -- please refer to my comment there about GFF3 sequence ID formats.

**Closed** 2019-12-01 18:39 UTC
Labels: duplicate
