### ISSUE TITLE
Difficulty extracting intronic regions

### ISSUE THREAD

**Issue by kd-lab** [genometools/genometools#1002] opened 2022-03-30 06:31 UTC
## Problem description
I pulled the latest gff3 file for Zea mays from refseq (https://ftp.ncbi.nlm.nih.gov/genomes/refseq/plant/Zea_mays/annotation_releases/current/)

I tidied the file with: gt gff3 -tidy yes

I tried pulling intronic sequences with: gt interfeat -outside CDS

The error I got was: gt interfeat: error: feature on line 1048669 of 'temp2.gff3' has a different strand than the feature on line 1048667

I don't understand what I am doing wrong here.

## Exact command line call triggering the problem

```
# tidy with
gt gff3 -tidy yes -o temp2.gff3 GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff
# line with error
gt interfeat -outside CDS -o output_cds_intron.gff3 temp.gff3
```

```
gt interfeat: error: feature on line 1048669 of 'temp2.gff3' has a different strand than the feature on line 1048667
```

## Example minimal input triggering the problem

```
# not tidied first
gt interfeat -outside CDS -o output_cds_intron.gff3 GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff
```

```
gt interfeat: error: attribute "replace=" on line 998141 in file "GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff" has no value
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

1.6.1

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

no

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Ubuntu

**Comment by satta** [comment] 2022-04-02 13:54
This issue is based on some weird features in the input annotation. If you just run
```
gt gff3 -retainids -tidy yes -force -o temp2.gff3 ~/Downloads/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff.gz
````
you will notice that this will output warnings like 
```
warning: the multi-feature with ID "gene-ZeamMp186" on line 997502 in file "/home/satta/Downloads/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff.gz" has a different strand than its counterpart on line 997499 (possible in rare cases)
```
(in fact, 19 of them) Let's take a look at that feature:
```
$ zfgrep  gene-ZeamMp186 ~/Downloads/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff.gz
NC_007982.1	RefSeq	gene	50490	50874	.	+	.	ID=gene-ZeamMp186;Dbxref=GeneID:4055939;Name=nad1;exception=trans-splicing;gbkey=Gene;gene=nad1;gene_biotype=protein_coding;locus_tag=ZeamMp186;part=1/4
NC_007982.1	RefSeq	gene	320928	322595	.	+	.	ID=gene-ZeamMp186;Dbxref=GeneID:4055939;Name=nad1;exception=trans-splicing;gbkey=Gene;gene=nad1;gene_biotype=protein_coding;locus_tag=ZeamMp186;part=2/4
NC_007982.1	RefSeq	gene	548714	548772	.	+	.	ID=gene-ZeamMp186;Dbxref=GeneID:4055939;Name=nad1;exception=trans-splicing;gbkey=Gene;gene=nad1;gene_biotype=protein_coding;locus_tag=ZeamMp186;part=3/4
NC_007982.1	RefSeq	gene	266974	267232	.	-	.	ID=gene-ZeamMp186;Dbxref=GeneID:4055939;Name=nad1;exception=trans-splicing;gbkey=Gene;gene=nad1;gene_biotype=protein_coding;locus_tag=ZeamMp186;part=4/4
NC_007982.1	RefSeq	CDS	50490	50874	.	+	0	ID=cds-YP_588282.1;Parent=gene-ZeamMp186;Dbxref=Genbank:YP_588282.1,GeneID:4055939;Name=YP_588282.1;exception=trans-splicing%2C RNA editing;gbkey=CDS;gene=nad1;locus_tag=ZeamMp186;product=NADH dehydrogenase subunit 1;protein_id=YP_588282.1
NC_007982.1	RefSeq	CDS	320928	321010	.	+	2	ID=cds-YP_588282.1;Parent=gene-ZeamMp186;Dbxref=Genbank:YP_588282.1,GeneID:4055939;Name=YP_588282.1;exception=trans-splicing%2C RNA editing;gbkey=CDS;gene=nad1;locus_tag=ZeamMp186;product=NADH dehydrogenase subunit 1;protein_id=YP_588282.1
NC_007982.1	RefSeq	CDS	322404	322595	.	+	0	ID=cds-YP_588282.1;Parent=gene-ZeamMp186;Dbxref=Genbank:YP_588282.1,GeneID:4055939;Name=YP_588282.1;exception=trans-splicing%2C RNA editing;gbkey=CDS;gene=nad1;locus_tag=ZeamMp186;product=NADH dehydrogenase subunit 1;protein_id=YP_588282.1
NC_007982.1	RefSeq	CDS	548714	548772	.	+	0	ID=cds-YP_588282.1;Parent=gene-ZeamMp186;Dbxref=Genbank:YP_588282.1,GeneID:4055939;Name=YP_588282.1;exception=trans-splicing%2C RNA editing;gbkey=CDS;gene=nad1;locus_tag=ZeamMp186;product=NADH dehydrogenase subunit 1;protein_id=YP_588282.1
NC_007982.1	RefSeq	CDS	266974	267232	.	-	1	ID=cds-YP_588282.1;Parent=gene-ZeamMp186;Dbxref=Genbank:YP_588282.1,GeneID:4055939;Name=YP_588282.1;exception=trans-splicing%2C RNA editing;gbkey=CDS;gene=nad1;locus_tag=ZeamMp186;product=NADH dehydrogenase subunit 1;protein_id=YP_588282.1
NC_007982.1	RefSeq	exon	50490	50874	.	+	.	ID=id-ZeamMp186-1;Parent=gene-ZeamMp186;Dbxref=GeneID:4055939;exon_number=1;gbkey=exon;gene=nad1;locus_tag=ZeamMp186;number=1
```
So we see three `gene` entries with the same ID, denoting a discontinuous feature which GenomeTools will group using a virtual pseudo-parent. However, they are on different strands: one is on `-` while three are on `+`. The comment in the GFF3 attribute `exception=trans-splicing%2C RNA editing` suggests that this is not an error, but refers to a real situation -- one of the "rare cases" mentioned in the warning.
However, for `gt interfeat` this is a problem: which sequence is it to output? Which strand is it to pick? This is the reason why it complains here with the message you are seeing.

If you exclude the trans-spliced features from the set then everything works as intended:
````
$ zfgrep 'exception=trans' ~/Downloads/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff.gz | egrep -o "ID=[^;]+" | cut -c4- > filter.txt
$ zfgrep -f filter.txt -v ~/Downloads/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.gff.gz | gt gff3 -tidy -sort |  gt interfeat -outside CDS > out.gff3
[...]
```
which now contains `intron`s as expected:
```
$ gt stat out.gff3
parsed genome node DAGs: 54187
sequence regions: 687 (total length: 2182786008)
multi-features: 49423
genes: 44696
protein-coding genes: 34330
mRNAs: 57304
protein-coding mRNAs: 57304
exons: 509459
CDSs: 347769
antisense_RNAs: 1
cDNA_matchs: 10692
introns: 290219
lnc_RNAs: 7834
matchs: 101
miRNAs: 310
primary_transcripts: 164
pseudogenes: 5194
rRNAs: 2440
regions: 687
sequence_conflicts: 81
sequence_features: 115
snRNAs: 241
snoRNAs: 655
tRNAs: 1374
transcripts: 8042
```

**Comment by satta** [comment] 2022-05-08 22:02
I hope your question has been answered. Closing this issue -- if there is anything else please feel free to reopen.

**Closed by satta** 2022-05-08 22:02 UTC
Labels: question, support
