### ISSUE TITLE
LtrPipeline: GenomeTools failed to run ltrharvest. Error code: 139

### ISSUE THREAD

**Issue by panpandzf** [genometools/genometools#1018] opened 2023-03-11 10:22 UTC
![image](https://user-images.githubusercontent.com/126332368/224478895-fc6279b5-824b-4e72-991a-b1224225e1c4.png)
Hello,
Does anyone know how to fix this problem? Any help would be greatly appreciated.

**Comment by satta** [comment] 2023-03-11 10:45
Hi,

just so you know LTRPipeline is not part of GenomeTools, it only uses LTRharvest which is. Unfortunately the above message alone does not help much with determining the root cause of the problem (the segmentation fault) since it neither states:

* what version of GenomeTools/LTRharvest is used
* what the complete command line was that LTRPipeline used to run LTRharvest, inclusing all parameters to `gt ltrharvest` and `gt suffixerator`
* what input, i.e. what sequence file(s), was/were used
* on what kind of machine it was run (this is important, for example, to determine whether a 32-bit or 64-bit version was used and how much RAM was available.

I am afraid I will not be able to reproduce your problem for debugging unless provided this information, sorry. If I had to take a very wild guess: The long run time (if that was LTRharvest alone) seems to suggest that a lot of candidate pairs were generated, and that might have led to memory issues. Usually this can be addressed by masking low complexity regions and simple repeats in the LTRharvest call, or by extending the seed size. I am not sure if your pipeline allows to tweak these parameters.

**Comment by panpandzf** [comment] 2023-03-11 11:15
I am very sorry for my ignorance. I am using LtrPipeline in repeatmodeler. When I use one chromosome, there is no problem running repeatmodeler, but there is a problem when running 1.2G genome. The log file is empty. Is this a memory problem? ? I should go to the repeatmodeler github for help, but I would also like to hear your advice.

**Comment by satta** [comment] 2023-03-11 11:24
It might be memory related. LTRharvest enumerates pairs of identical stretches in sequences and then checks if they can possibly form an LTR element conforming to the configured model. If there are lots of such repetitive pairs, e.g. if your whole genome has highly repetitive heterochromatin sequence or lots of simple repeats (`ATATATATATAT`, `GGGGGGGGGGGGGGGG`, ...), or is highly repetitive in general, then LTRharvest might get a lot of pairs to check, which need to be stored and also iteratively checked, leading to excessive run time and memoru usage.

The general approach there (and I would do so for 1.2GB sequences) is to split up the sequence and run parts of it separately against LTRharvest. This means that the results would then need to be merged again afterwards. I would expect the LtrPipeline tool to do that, if it claims to support such data sets. As I said, it might also help masking problematic regions before by replacing them with `N`s to avoid LTRharvest trying to call candidate pairs there.

I think it might make most sense to contact the authors or LtrPipeline -- I would expect them to know what to do and, if necessary, open a more detailed issue here if the problem can be narrowed down into more detail.

**Comment by panpandzf** [comment] 2023-03-11 11:40
Thanks a lot for your suggestion. My command-line entry is pretty neat "repeatmodeler -pa 12 -database -database db/dbname -engine ncbi -LTRStruct &" I'll close the question and open it if necessary. Finally, thanks again for your help

**Closed** 2023-03-11 11:40 UTC

**Comment by KangJunyaowu** [comment] 2025-06-21 01:43
@panpandzf Hello, I'm having the same problem as you, I don't know if you've solved it
