### ISSUE TITLE
bed_to_gff3 bug

### ISSUE THREAD

**Issue by yumisims** [genometools/genometools#1012] opened 2022-10-26 19:42 UTC
## Problem description
a bug reminder appeared when using bed_to_gff3

## Exact command line call triggering the problem

```
gt bed_to_gff3 sorted.bed
```

## Example minimal input triggering the problem
sorted.bed
which gives this message: Assertion failed: (start <= end), function gt_feature_node_new, file src/extended/feature_node.c, line 241.
This is a bug, please report it at

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
1.6.2

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
did not use any parameters

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Ubuntu 7.5.0-3ubuntu1~18.04 x86_64

**Comment by satta** [comment] 2022-10-27 13:00
Thanks for reporting this. Can you provide a BED file triggering the issue please? This is difficult to reproduce without the problematic input.

**Comment by yumisims** [comment] 2022-10-27 13:03
here is the file, thank you so much
[sorted.bed.zip](https://github.com/genometools/genometools/files/9879612/sorted.bed.zip)

**Comment by satta** [comment] 2022-10-27 13:48
It looks like the file contains some lines with zero length blocks, e.g. line 46
```
SCAFFOLD_1	5683816	5931765	FZQP02005244.1(FZQP02005244.1)	1	+	5683816	5931765	255,0,0	5	8,0,7,8,591	0,19632,141484,143033,247358
```
That case was not handled correctly in the conversion code and hence resulted in wrong GFF3 coordinates. I have prepared a patch to handle that.

After that patch the conversion finishes:
```
[satta@BLN04NB0421:~/tmp/genometools] $ ./bin/gt bed_to_gff3 sorted.bed | ./bin/gt stat
parsed genome node DAGs: 11965
sequence regions: 81 (total length: 952029471)
BED_blocks: 35871
BED_features: 11884
BED_thick_features: 11884
```

**Comment by yumisims** [comment] 2022-10-27 15:37
Thanks for sorting this out, I will give another try and report back to here.

**Comment by yumisims** [comment] 2022-10-28 09:45
I git clone the newest version (1.6.3) from github and install it again but same problem appeared, could you please let me know where is the updated version?

**Comment by satta** [comment] 2022-10-31 09:15
The code change has not been merged yet because there are still build problems on Mac OS due to the fact that we still need to adapt to Apple switching to the ARM platform. So no merge to master and no new version release yet. If you want to test-drive the code as it appears in this pull request, feel free to clone from the `bedstuff` branch from my personal repository: https://github.com/satta/genometools

**Comment by yumisims** [comment] 2022-10-31 11:05
I checked out the code from your repository, then tried : gt bed_to_gff3 sorted.bed|gt stat, and it gave the following:
Assertion failed: (start <= end), function gt_feature_node_new, file src/extended/feature_node.c, line 241.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with `gt -version`.
gt stat: error: GFF3 file "stdin" is empty

Anything that I have missed?

Thanks

**Comment by satta** [comment] 2022-10-31 11:11
Have you checked out the `bedstuff` branch, rebuilt the code (`make...`) and ran the correct binary (in the `bin` directory)? The `master` branch in my repository is also not updated yet.

**Comment by yumisims** [comment] 2022-10-31 11:47
ok, I missed the branch, all working fine now, thank you very much.

**Closed** 2022-11-04 10:50 UTC
Labels: bug
