### ISSUE TITLE
Current git version fails to build on Mac OS X 

### ISSUE THREAD

**Issue by satta** [genometools/genometools#776] opened 2016-04-03 16:21 UTC
There's been an addition to the static checks in their clang, resulting in a warning here and in other places. @Garonenur could you check whether the behaviour is correct?
```
src/extended/encdesc.c:1344:13: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
        if (!encdesc->cur_desc == 0 && !sampled) {
            ^                  ~~
src/extended/encdesc.c:1344:13: note: add parentheses after the '!' to evaluate the comparison first
        if (!encdesc->cur_desc == 0 && !sampled) {
            ^
             (                     )
src/extended/encdesc.c:1344:13: note: add parentheses around left hand side expression to silence this warning
        if (!encdesc->cur_desc == 0 && !sampled) {
            ^
            (                 )
1 error generated.
make: *** [obj/src/extended/encdesc.o] Error 1
```

**Comment by Garonenur** [comment] 2016-04-03 17:56
ok, I changed that, because ```cur_desc == 0``` should be negated. But, if there are more things that version of clang finds in my code, I don't see it, because my version does not pick those up.
Which version are you using?

by the way:
is !A = false the same as !(A = false)? Because ``` cur_desc is just a numerical value and ```!cur_desc``` therefore should turn anything to 0 if its any number. I actually made a table, and I think this is something I should have written with parentheses, but it's not a bug, because the result is the same (in this case).

**Comment by Garonenur** [comment] 2016-04-03 18:16
I just installed the stable version of clang:
```Ubuntu clang version 3.7.1-svn254351-1~exp1 (branches/release_37) (based on LLVM 3.7.1)```
and it does not find any more errors. Tell me if there is more to look at.

**Comment by satta** [comment] 2016-04-03 18:23
I'm using:
```
$ clang -v
Apple LLVM version 7.3.0 (clang-703.0.29)
```
This is the latest version of the command line dev tools for El Capitan (10.11.4)


The only other things I could see are a few Lua warnings, see http://pastebin.com/85gjZaCc

**Comment by satta** [comment] 2016-04-03 18:25
And IMHO if the behavious is as intended it may not be a bug but it will break the build with `-Werror` which may confuse Mac users ;)

**Comment by Garonenur** [comment] 2016-04-03 20:21
OK

then my PR should fix my part and the rest is up to you. We might have to reopen this issue, as my commit will close it.

**Comment by satta** [comment] 2016-04-04 09:41
Thanks! I'll keep this open then until I looked at the Lua stuff. We should also think of supporting newer Lua versions -- they are at 5.3 now but IIRC there were still a few issues with how we use the C API that made it non-trivial to update.
I'll open a new enhancement ticket for this.

**Closed** 2016-04-10 23:20 UTC
