### ISSUE TITLE
issue running 'gt ltrdigest' on compute farm

### ISSUE THREAD

**Issue by avrilcoghlan** [genometools/genometools#662] opened 2015-09-18 15:26 UTC
Hello,
I've been trying to run 'gt ltrdigest' on a compute farm. I found that if I run one LTRdigest job on the farm, it runs fine, but if I submit lots of LTRdigest jobs at once (all using the same -hmms directory of HMM files), then I get errors and the jobs die, with errors relating to the HMM files. 
I then tried setting the TMPDIR environment variable to be a different local directory for each LTRdigest job, and was able to run lots of jobs at once on our compute farm. All the jobs seemed to finish fine, and at first I thought this had solved the problem.
However, I noticed that the output gff from LTRdigest didn't have any 'protein_match' features when I ran lots of jobs at once on the compute farm (while if I just ran one job on the farm at a time, the output gff did have 'protein_match' features). I'm not sure why this is, because the *fas files for the protein domains are produced fine. However, I think it must be that somehow the hmmer search didn't run ok?
Please let me know if you'd like me to send more info or files.
Kind Regards,
Avril
Avril Coghlan
Sanger Institute

**Comment by Mrwow** [comment] 2016-01-31 11:44
I meet a problem too in LTRdigest. In the result,  the protein-domain.fas files **olny has one sequence** match the protein domain. but in  tabout.csv file, every protein domian** have many hits**. I don't know why. my command line is below:
gt -j 2 ltrdigest 
-pptlen 10 30 
-pbsoffset 0 3 
-trnas ../../tRNAs.fa
-hmms ../../hmm/*.hmm
-outfileprefix chr
-aaout yes
sorted.gff3 chr1.sa > digest-chr1.txt

**Comment by satta** [comment] 2016-01-31 11:50
Thanks for providing an independent case showing this behaviour! Can you probably provide a small input case triggering the problem, so I can try to reproduce and debug the issue? That is, an example `sorted.gff3` and `chr1.sa` file, together with the result CSV and GFF3. Thanks!

**Comment by Mrwow** [comment] 2016-01-31 13:26
the zip file i upload have below file:
1. harvest-ssc1.gff  and harvest-scc1_sorted.gff3      which were from ltrharvest
2. file name having digest  are all from  ltrdigest including   result CSV  and GFF3 .  
3. the digest-ssc1_pdom_pol-rt-RVT_1.fas and aa.fas  are  the my question file, which olny have one sequence match the protein domain(RVT_1).
4. the chr1.fsa is too big. I used the whole sequence of  chromsome 1 of pig genome from NCBI. so i don't send it to your. 
Thanks a lot~~

[ltrdigest_problem_files.zip](https://github.com/genometools/genometools/files/111275/ltrdigest_problem_files.zip)

**Comment by Mrwow** [comment] 2016-02-01 09:54
I try to install the genometools again. This time, I used 
apt-get install genometools 
while I used make last time in the same Ubuntu 14.04 LTS system. when  I finish the install and type 
gt ltrdigest -help+
I cannot find  -hmms command in ltrdigest. Did I miss something ?

**Comment by satta** [comment] 2016-02-01 10:04
I will take a look at your example sequence later, thanks.

About your new installation, I can't really see why this option would be missing. Did you uninstall your previous self-installed GenomeTools binary? Also, what happens if you try to run a command involving `-hmms` regardless of the help output?

**Comment by Mrwow** [comment] 2016-02-02 04:51
of course, to uninstall my previous self-installed GenomeTools binary, I reinstall the all ubuntu system.  If I tried  to run a command involving `-hmms` regardless of the help output,  there would be a `error:unknown option: -hmms`. so I guess that just type `apt-get install genometools ` dont install hmmer at the same time.
by the way, can the version of _Fix writing of LTRdigest output files _  download now? 
Thanks a lot!!

**Comment by satta** [comment] 2016-02-02 10:38
Any recent GenomeTools binary includes HMMER support in principle, so the `-hmms` option should _always_ be listed. If HMMER is not installed, then you should get the following error instead:
```
gt ltrdigest: error: Error running hmmpress. Please make sure that all HMMER executables are in your PATH.
```
Old versions of LTRdigest had to be compiled with HMMER support enabled. It seems that Ubuntu 14.04 still ships this old version (1.5.1) and you should upgrade to a newer release of Ubuntu. 

To answer your second question: To get the bug fix, you will need to use the most recent development version (1.5.9) anyway so the Ubuntu package won't help you much. You can get the source here from GitHub once my fix is accepted in the main code. I will let you know here when that happens.

**Comment by satta** [comment] 2016-02-02 11:06
The fix has just been merged. Please get the new source from https://github.com/genometools/genometools/archive/master.zip.

**Comment by satta** [comment] 2016-02-03 17:55
@avrilcoghlan To get back to your original issue, I have just run a parallel test case with 20 _Trichuris muris_ candidate sets being annotated with LTRdigest at the same time on farm3, each in a separate directory with separate `TMPDIR`s and with the same set of HMMs and parameters you used in your runs. All of the results contained the expected `protein_match` features in their GFF3 output. So I'm afraid I can't reproduce your issue :(

**Comment by satta** [comment] 2016-03-10 11:08
Closing this after personal discussion with @avrilcoghlan.

**Closed by satta** 2016-03-10 11:08 UTC
