### ISSUE TITLE
ltrdigest assertion failed

### ISSUE THREAD

**Issue by narni1992** [genometools/genometools#729] opened 2016-01-14 16:35 UTC
Hello,
I'm trying to run ltrdigest in an effort to create an extensive de novo repeat library for a termite genome. I've encountered following bug:
```
Assertion failed: (esc && filenum < gt_encseq_num_of_files(esc->encseq)), function gt_encseq_col_get_description, file src/core/encseq_col.c, line 410.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
```
I'm running gt 5.8.1 on a cluster with the command:
```
gt suffixerator -db ref.fa -indexname ref.fa -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest -index ref.fa -seqids yes -tabout no > ltrharvest.out
gt gff3 -sort ltrharvest.out > sorted_input_gff
gt encseq encode -lossless yes ref.fa
gt ltrdigest -hmms /global/scratch/n_arni01/te_analysis/LTR_hmms/*.hmm -outfileprefix csec_ltrdigest -encseq ref.fa -matchdescstart< sorted_input_gff > csec_ltrdigest_output_gff
```
I'm following the instruction on the very helpful blog of Avril Coghlan (http://avrilomics.blogspot.de/2015/09/ltrharvest.html). I'd be thankful for any kind of help

**Comment by satta** [comment] 2016-01-14 17:12
Looks good to me and the commands you use also work perfectly for me on a test sequence. To find out what's going on here I suggest that you try the following:
- Delete all indexes (`ref.fa.*`) to start from a clean slate.
- Use the `-lossless` switch in your initial `gt suffixerator` call, this way you don't have to re-encode afterwards:
  ```
gt suffixerator -db ref.fa -indexname ref.fa -lossless -tis -suf -lcp -des -ssp -sds -dna

  ```
- Re-run the rest of your steps without the `gt encseq encode`.

If the problem persists, can you isolate a test case from your input sequence which triggers the problem? It might be that it is an issue specific to your input and I would need to take a look at it to further debug the problem.

**Comment by narni1992** [comment] 2016-01-15 10:11
Thanks for the quick reply. I've modified the code like you suggested which now looks like this:

gt suffixerator -db test.fa -indexname test.fa  -lossless -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest -index test.fa -seqids yes -tabout no > ltrharvest.out
gt gff3 -sort ltrharvest.out > sorted_input_gff
gt ltrdigest -hmms /global/scratch/n_arni01/te_analysis/LTR_hmms/*.hmm -outfileprefix csec_ltrdigest -encseq test.fa -matchdescstart< sorted_input_gff > csec_ltrdigest_output_gff
gt select -rule_files /global/scratch/n_arni01/te_analysis/filter_protein_match.lua -- < csec_ltrdigest_output_gff > csec_ltrdigest_output_gff2
gt extractfeat -type LTR_retrotransposon -encseq test.fa csec_ltrdigest_output_gff2 > csec_ltrdigest_output_gff2.fa

and the error persists. I have trimmed down the genome to only two scaffolds which i drastically shortened and I still get the same error. I have attached the test reference (as a .txt. because github doesnt support .fa) maybe you can recreate the error. Thanks in advance! 
[test.txt](https://github.com/genometools/genometools/files/91667/test.txt)

**Comment by satta** [comment] 2016-01-16 11:29
OK, I can confirm the issue and will start debugging it later.

**Comment by satta** [comment] 2016-01-16 17:40
I have found the cause of your issue and fixed it in the latest GenomeTools version. As a workaround on earlier versions, you can just use the `-seqfile` option instead of `-encseq` as you still have the original sequence file:
```
gt ltrdigest  -outfileprefix csec_ltrdigest -seqfile test.fa -matchdescstart< sorted_input_gff > csec_ltrdigest_output_gff
```
You only need the `-encseq` option if you only have the indexes but not the original sequence file.
Please let me know if my changes have fixed the issue for you. Thanks for reporting this!

**Comment by narni1992** [comment] 2016-01-18 08:54
Thanks for the quick and helpful response. This is what I call great support! Everything is running fine now.

**Comment by satta** [comment] 2016-01-18 09:37
Glad to hear it works now for you, thanks for the feedback. Closing this ticket then.

**Closed by satta** 2016-01-18 09:37 UTC
Labels: bug
